export const rolePermissions = {
  Administrator: {
    canViewAll: true,
    canManageUsers: true,
    canManageCemeteries: true,
    canManageSections: true,
    canManageCrematoriums: true,
    canManageTariffs: true,
    canApproveExhumations: true,
    canDeleteRecords: true,
    canViewReports: true,
    canViewRevenue: true,
    navigation: [
      'Dashboard',
      'Cemeteries',
      'Crematoriums',
      'Plots',
      'Deceased',
      'Bookings',
      'Burials',
      'Exhumations',
      'Owners',
      'Work Orders',
      'Enquiries',
      'Reports',
      'Tariffs',
      'Service Charges',
    ],
  },
  'Cemetery Manager': {
    canViewAll: true,
    canManageUsers: false,
    canManageCemeteries: true,
    canManageSections: true,
    canManageCrematoriums: true,
    canManageTariffs: false,
    canApproveExhumations: true,
    canDeleteRecords: false,
    canViewReports: true,
    canViewRevenue: false,
    navigation: [
      'Dashboard',
      'Cemeteries',
      'Crematoriums',
      'Plots',
      'Deceased',
      'Bookings',
      'Burials',
      'Exhumations',
      'Owners',
      'Work Orders',
      'Enquiries',
      'Reports',
      'Service Charges',
    ],
  },
  'Cemetery Clerk': {
    canViewAll: false,
    canManageUsers: false,
    canManageCemeteries: false,
    canManageSections: false,
    canManageCrematoriums: false,
    canManageTariffs: false,
    canApproveExhumations: false,
    canDeleteRecords: false,
    canViewReports: true,
    canViewRevenue: false,
    navigation: [
      'Dashboard',
      'Cemeteries',
      'Crematoriums',
      'Plots',
      'Deceased',
      'Bookings',
      'Burials',
      'Exhumations',
      'Owners',
      'Work Orders',
      'Enquiries',
      'Reports',
    ],
  },
  'Burial Officer': {
    canViewAll: false,
    canManageUsers: false,
    canManageCemeteries: false,
    canManageSections: false,
    canManageCrematoriums: false,
    canManageTariffs: false,
    canApproveExhumations: false,
    canDeleteRecords: false,
    canViewReports: false,
    canViewRevenue: false,
    navigation: [
      'Dashboard',
      'Cemeteries',
      'Plots',
      'Deceased',
      'Bookings',
      'Burials',
      'Work Orders',
    ],
  },
  'Finance User': {
    canViewAll: false,
    canManageUsers: false,
    canManageCemeteries: false,
    canManageSections: false,
    canManageCrematoriums: false,
    canManageTariffs: true,
    canApproveExhumations: false,
    canDeleteRecords: false,
    canViewReports: true,
    canViewRevenue: true,
    navigation: [
      'Dashboard',
      'Cemeteries',
      'Plots',
      'Deceased',
      'Bookings',
      'Owners',
      'Reports',
      'Tariffs',
      'Service Charges',
    ],
  },
  'Funeral Undertaker': {
    canViewAll: false,
    canManageUsers: false,
    canManageCemeteries: false,
    canManageSections: false,
    canManageCrematoriums: false,
    canManageTariffs: false,
    canApproveExhumations: false,
    canDeleteRecords: false,
    canViewReports: false,
    canViewRevenue: false,
    navigation: [
      'Dashboard',
    ],
    undertakerNavigation: [
      'Dashboard',
      'My Bookings',
      'My Burials',
      'Available Plots',
      'Available Crematoriums',
      'Tariffs',
      'Profile',
    ],
  },
  'Read-only': {
    canViewAll: false,
    canManageUsers: false,
    canManageCemeteries: false,
    canManageSections: false,
    canManageCrematoriums: false,
    canManageTariffs: false,
    canApproveExhumations: false,
    canDeleteRecords: false,
    canViewReports: true,
    canViewRevenue: false,
    navigation: [
      'Dashboard',
      'Cemeteries',
      'Crematoriums',
      'Plots',
      'Deceased',
      'Bookings',
      'Burials',
      'Exhumations',
      'Owners',
      'Work Orders',
      'Enquiries',
      'Reports',
    ],
  },
};

export const hasPermission = (userRole, permission) => {
  const permissions = rolePermissions[userRole];
  return permissions ? permissions[permission] : false;
};

export const getNavigationForRole = (userRole) => {
  const permissions = rolePermissions[userRole];
  return permissions ? permissions.navigation : [];
};

